include!("src/ipc_commands.rs");

/// Generated permission set allowing every app command. Granted to the main
/// webview in `capabilities/default.json`.
const PERMISSION_SET_PATH: &str = "permissions/app-commands.toml";

fn main() {
    let permissions: Vec<String> = APP_COMMANDS
        .iter()
        .map(|c| format!("  \"allow-{}\",", c.replace('_', "-")))
        .collect();
    let set = format!(
        "# Generated by build.rs from src/ipc_commands.rs. Do not edit.\n\n\
         [[set]]\n\
         identifier = \"app-commands\"\n\
         description = \"Every ReMa command. Granted only to ReMa's own interface.\"\n\
         permissions = [\n{}\n]\n",
        permissions.join("\n")
    );
    if std::fs::read_to_string(PERMISSION_SET_PATH).ok().as_deref() != Some(set.as_str()) {
        std::fs::create_dir_all("permissions").expect("create permissions folder");
        std::fs::write(PERMISSION_SET_PATH, set).expect("write the permission set");
    }
    println!("cargo:rerun-if-changed=src/ipc_commands.rs");

    tauri_build::try_build(
        tauri_build::Attributes::new().app_manifest(
            tauri_build::AppManifest::new()
                .commands(APP_COMMANDS)
                // Only the top-level set; `autogenerated/` is added by `commands`.
                .permissions_path_pattern("./permissions/*.toml"),
        ),
    )
    .expect("failed to run tauri-build");
}
