// Fetches the latest official Codex and Anthropic (`ant`) command-line
// runtimes for one target into src-tauri/runtimes/, so ReMa's app bundle ships
// them (ChatGPT and Claude Console sign-in work without a separate install).
//
//   node scripts/runtimes/fetch.mjs [--target <rust target triple>]
//
// - Codex: the npm registry's `latest` @openai/codex release. The platform
//   package is checked against the registry's sha512 integrity, and only the
//   `codex` executable is kept.
// - ant: Anthropic's official Homebrew cask (generated by GoReleaser on every
//   release) names the latest version, the archive for each platform and its
//   SHA-256. Windows archives are checked against the release's checksums.
//
// Nothing is kept unless its checksum matches. An up-to-date runtime is not
// downloaded again. Uses `curl` and `tar`, which ship with macOS, Windows 10+
// and Linux distributions, and honor the usual proxy settings.

import { spawnSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import {
  chmodSync,
  copyFileSync,
  createReadStream,
  existsSync,
  mkdirSync,
  mkdtempSync,
  readdirSync,
  readFileSync,
  rmSync,
  statSync,
  writeFileSync,
} from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '../..');
const outDir = join(root, 'src-tauri/runtimes');
const versionsFile = join(outDir, 'versions.json');

const CODEX_REGISTRY = 'https://registry.npmjs.org/@openai%2fcodex';
const ANT_CASK = 'https://raw.githubusercontent.com/anthropics/homebrew-tap/main/Casks/ant.rb';
const ANT_RELEASES = 'https://github.com/anthropics/anthropic-cli/releases/download';

/** Rust target triple → where each runtime publishes that platform. */
const PLATFORMS = {
  'aarch64-apple-darwin': { codex: 'darwin-arm64', ant: ['macos', 'arm64'] },
  'x86_64-apple-darwin': { codex: 'darwin-x64', ant: ['macos', 'amd64'] },
  'x86_64-unknown-linux-gnu': { codex: 'linux-x64', ant: ['linux', 'amd64'] },
  'x86_64-unknown-linux-musl': { codex: 'linux-x64', ant: ['linux', 'amd64'] },
  'aarch64-unknown-linux-gnu': { codex: 'linux-arm64', ant: ['linux', 'arm64'] },
  'aarch64-unknown-linux-musl': { codex: 'linux-arm64', ant: ['linux', 'arm64'] },
  'x86_64-pc-windows-msvc': { codex: 'win32-x64', ant: ['windows', 'amd64'] },
  'aarch64-pc-windows-msvc': { codex: 'win32-arm64', ant: ['windows', 'arm64'] },
};

function fail(message) {
  console.error(`runtimes: ${message}`);
  process.exit(1);
}

function run(command, args, { capture = false } = {}) {
  const result = spawnSync(command, args, {
    encoding: capture ? 'utf8' : undefined,
    stdio: capture ? ['ignore', 'pipe', 'pipe'] : ['ignore', 'ignore', 'pipe'],
    maxBuffer: 64 * 1024 * 1024,
  });
  if (result.error) fail(`could not run ${command}: ${result.error.message}`);
  if (result.status !== 0) {
    const detail = String(result.stderr ?? '').trim().split('\n').slice(-3).join(' ');
    fail(`${command} ${args[0] ?? ''} failed${detail ? `: ${detail}` : ''}`);
  }
  return result.stdout;
}

/** Like `run`, but reports failure instead of exiting. */
function attempt(command, args) {
  const result = spawnSync(command, args, { stdio: 'ignore' });
  return !result.error && result.status === 0;
}

function targetTriple() {
  const flag = process.argv.indexOf('--target');
  if (flag !== -1 && process.argv[flag + 1]) return process.argv[flag + 1];
  if (process.env.TAURI_ENV_TARGET_TRIPLE) return process.env.TAURI_ENV_TARGET_TRIPLE;
  const host = /^host: (.+)$/m.exec(run('rustc', ['-vV'], { capture: true }));
  if (!host) fail('could not determine the Rust target (pass --target <triple>)');
  return host[1].trim();
}

const curlArgs = ['-fsSL', '--retry', '3', '--connect-timeout', '20'];
const getText = (url) => run('curl', [...curlArgs, url], { capture: true });
const getJson = (url) => JSON.parse(getText(url));
const download = (url, file) => run('curl', [...curlArgs, '-o', file, url]);

function digest(file, algorithm, encoding) {
  const hash = createHash(algorithm);
  const data = readFileSync(file);
  hash.update(data);
  return hash.digest(encoding);
}

/** Streams large files through the hash (Codex archives are ~150 MB). */
async function digestStream(file, algorithm, encoding) {
  const hash = createHash(algorithm);
  for await (const chunk of createReadStream(file)) hash.update(chunk);
  return hash.digest(encoding);
}

function readVersions() {
  try {
    return JSON.parse(readFileSync(versionsFile, 'utf8'));
  } catch {
    return {};
  }
}

function install(extracted, destination) {
  copyFileSync(extracted, destination);
  chmodSync(destination, 0o755);
}

/** Finds `name` anywhere under `dir` (archive layouts differ by platform). */
function findFile(dir, name) {
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const path = join(dir, entry.name);
    if (entry.isDirectory()) {
      const found = findFile(path, name);
      if (found) return found;
    } else if (entry.name === name) {
      return path;
    }
  }
  return null;
}

async function fetchCodex(triple, platform, exe, recorded, work) {
  const latest = getJson(`${CODEX_REGISTRY}/latest`);
  const version = latest.version;
  const destination = join(outDir, `codex-${triple}${exe}`);
  if (recorded === version && existsSync(destination)) {
    console.log(`runtimes: Codex ${version} is up to date`);
    return version;
  }
  const alias = latest.optionalDependencies?.[`@openai/codex-${platform}`];
  const spec = alias?.startsWith('npm:@openai/codex@') ? alias.slice('npm:@openai/codex@'.length) : null;
  if (!spec) fail(`Codex ${version} has no package for ${platform}`);
  const manifest = getJson(`${CODEX_REGISTRY}/${encodeURIComponent(spec)}`);
  const integrity = manifest.dist?.integrity ?? '';
  if (!integrity.startsWith('sha512-')) fail('the Codex package has no sha512 integrity');

  console.log(`runtimes: downloading Codex ${version} (${platform})…`);
  const archive = join(work, 'codex.tgz');
  download(manifest.dist.tarball, archive);
  if ((await digestStream(archive, 'sha512', 'base64')) !== integrity.slice('sha512-'.length)) {
    fail('the Codex download does not match the registry checksum');
  }
  const member = run('tar', ['-tzf', archive], { capture: true })
    .split('\n')
    .map((line) => line.trim())
    .find((line) => new RegExp(`^package/vendor/[^/]+/bin/codex${exe.replace('.', '\\.')}$`).test(line));
  if (!member) fail('the Codex package does not contain the codex executable');
  run('tar', ['-xzf', archive, '-C', work, member]);
  install(join(work, member), destination);
  console.log(`runtimes: Codex ${version} → ${destination}`);
  return version;
}

async function fetchAnt(triple, [os, arch], exe, recorded, work) {
  const cask = getText(ANT_CASK);
  const version = /^\s*version\s+"([^"]+)"/m.exec(cask)?.[1];
  if (!version) fail('could not read the ant version from the Homebrew cask');
  const destination = join(outDir, `ant-${triple}${exe}`);
  if (recorded === version && existsSync(destination)) {
    console.log(`runtimes: ant ${version} is up to date`);
    return version;
  }

  const fileName = `ant_${version}_${os}_${arch}.${os === 'linux' ? 'tar.gz' : 'zip'}`;
  let sha256 = null;
  // Each `url "…"` in the cask is followed by the `sha256 "…"` of that archive.
  for (const match of cask.matchAll(/url\s+"([^"]+)"\s+sha256\s+"([0-9a-f]{64})"/g)) {
    if (match[1].replaceAll('#{version}', version).endsWith(`/${fileName}`)) sha256 = match[2];
  }
  if (!sha256) {
    // Not in the cask (Windows): use the release's own checksums file.
    for (const name of [`ant_${version}_checksums.txt`, 'checksums.txt']) {
      try {
        const line = getText(`${ANT_RELEASES}/v${version}/${name}`)
          .split('\n')
          .find((l) => l.trim().endsWith(` ${fileName}`));
        if (line) sha256 = line.trim().split(/\s+/)[0];
      } catch {
        // Try the next name.
      }
      if (sha256) break;
    }
  }
  if (!sha256) fail(`no published checksum for ${fileName}`);

  console.log(`runtimes: downloading ant ${version} (${os} ${arch})…`);
  const archive = join(work, fileName);
  download(`${ANT_RELEASES}/v${version}/${fileName}`, archive);
  if (digest(archive, 'sha256', 'hex') !== sha256) {
    fail('the ant download does not match its published checksum');
  }
  const unpacked = join(work, 'unpacked');
  mkdirSync(unpacked);
  if (os === 'linux') {
    run('tar', ['-xzf', archive, '-C', unpacked]);
  } else if (!attempt('tar', ['-xf', archive, '-C', unpacked])) {
    // bsdtar (macOS, Windows) reads zip archives; GNU tar needs unzip.
    run('unzip', ['-q', archive, '-d', unpacked]);
  }
  const binary = findFile(unpacked, `ant${exe}`);
  if (!binary) fail('the ant archive does not contain the ant executable');
  install(binary, destination);
  console.log(`runtimes: ant ${version} → ${destination}`);
  return version;
}

const triple = targetTriple();
if (triple === 'universal-apple-darwin') {
  fail('build one architecture at a time (aarch64-apple-darwin or x86_64-apple-darwin)');
}
const platform = PLATFORMS[triple];
if (!platform) fail(`no runtimes are published for ${triple}`);
const exe = triple.includes('windows') ? '.exe' : '';

mkdirSync(outDir, { recursive: true });
const versions = readVersions();
const recorded = versions[triple] ?? {};
const work = mkdtempSync(join(tmpdir(), 'rema-runtimes-'));
const record = (name, version) => {
  versions[triple] = { ...versions[triple], [name]: version };
  writeFileSync(versionsFile, `${JSON.stringify(versions, null, 2)}\n`);
};
try {
  const codexWork = join(work, 'codex');
  const antWork = join(work, 'ant');
  mkdirSync(codexWork);
  mkdirSync(antWork);
  record('codex', await fetchCodex(triple, platform.codex, exe, recorded.codex, codexWork));
  record('ant', await fetchAnt(triple, platform.ant, exe, recorded.ant, antWork));
  for (const name of [`codex-${triple}${exe}`, `ant-${triple}${exe}`]) {
    const size = statSync(join(outDir, name)).size;
    console.log(`runtimes: ${name} ${(size / 1024 / 1024).toFixed(0)} MB`);
  }
} finally {
  rmSync(work, { recursive: true, force: true });
}
