// Fetches the latest official Codex and Anthropic (`ant`) command-line
// runtimes for one target into src-tauri/runtimes/, so ReMa's app bundle ships
// them (ChatGPT and Claude Console sign-in work without a separate install).
//
//   node scripts/runtimes/fetch.mjs [--target <rust target triple>] [--check]
//
// - Codex: the npm registry's `latest` @openai/codex release. The platform
//   package is checked against the registry's sha512 integrity, and only the
//   `codex` executable is kept.
// - ant: Anthropic's official Homebrew cask (generated by GoReleaser on every
//   release) names the latest version, the archive for each platform and its
//   SHA-256. Windows archives are checked against the release's checksums.
//
// Nothing is kept unless its checksum matches, and a kept executable must be
// built for the target (its ELF, Mach-O or PE header says so) and runnable.
// versions.json records the version, SHA-256 and size of each kept file, so
// an up-to-date runtime is not downloaded again and a damaged one is. With
// `--check` nothing is downloaded: the fetched runtimes for the target are
// checked against versions.json (presence, checksum, architecture, execute
// bit) and every problem is listed; build.rs makes the same checks, minus the
// checksums, before a bundling build. Uses `curl` and `tar`, which ship with
// macOS, Windows 10+ and Linux distributions, and honor the usual proxy
// settings.

import { spawnSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import {
  chmodSync,
  closeSync,
  copyFileSync,
  createReadStream,
  existsSync,
  mkdirSync,
  mkdtempSync,
  openSync,
  readdirSync,
  readFileSync,
  readSync,
  rmSync,
  statSync,
  writeFileSync,
} from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '../..');
const outDir = join(root, 'src-tauri/runtimes');
const versionsFile = join(outDir, 'versions.json');

const CODEX_REGISTRY = 'https://registry.npmjs.org/@openai%2fcodex';
const ANT_CASK = 'https://raw.githubusercontent.com/anthropics/homebrew-tap/main/Casks/ant.rb';
const ANT_RELEASES = 'https://github.com/anthropics/anthropic-cli/releases/download';

/** Rust target triple → where each runtime publishes that platform. */
const PLATFORMS = {
  'aarch64-apple-darwin': { codex: 'darwin-arm64', ant: ['macos', 'arm64'] },
  'x86_64-apple-darwin': { codex: 'darwin-x64', ant: ['macos', 'amd64'] },
  'x86_64-unknown-linux-gnu': { codex: 'linux-x64', ant: ['linux', 'amd64'] },
  'x86_64-unknown-linux-musl': { codex: 'linux-x64', ant: ['linux', 'amd64'] },
  'aarch64-unknown-linux-gnu': { codex: 'linux-arm64', ant: ['linux', 'arm64'] },
  'aarch64-unknown-linux-musl': { codex: 'linux-arm64', ant: ['linux', 'arm64'] },
  'x86_64-pc-windows-msvc': { codex: 'win32-x64', ant: ['windows', 'amd64'] },
  'aarch64-pc-windows-msvc': { codex: 'win32-arm64', ant: ['windows', 'arm64'] },
};

function fail(message) {
  console.error(`runtimes: ${message}`);
  process.exit(1);
}

function run(command, args, { capture = false } = {}) {
  const result = spawnSync(command, args, {
    encoding: capture ? 'utf8' : undefined,
    stdio: capture ? ['ignore', 'pipe', 'pipe'] : ['ignore', 'ignore', 'pipe'],
    maxBuffer: 64 * 1024 * 1024,
  });
  if (result.error) fail(`could not run ${command}: ${result.error.message}`);
  if (result.status !== 0) {
    const detail = String(result.stderr ?? '').trim().split('\n').slice(-3).join(' ');
    fail(`${command} ${args[0] ?? ''} failed${detail ? `: ${detail}` : ''}`);
  }
  return result.stdout;
}

/** Like `run`, but reports failure instead of exiting. */
function attempt(command, args) {
  const result = spawnSync(command, args, { stdio: 'ignore' });
  return !result.error && result.status === 0;
}

function targetTriple() {
  const flag = process.argv.indexOf('--target');
  if (flag !== -1 && process.argv[flag + 1]) return process.argv[flag + 1];
  if (process.env.TAURI_ENV_TARGET_TRIPLE) return process.env.TAURI_ENV_TARGET_TRIPLE;
  const host = /^host: (.+)$/m.exec(run('rustc', ['-vV'], { capture: true }));
  if (!host) fail('could not determine the Rust target (pass --target <triple>)');
  return host[1].trim();
}

const curlArgs = ['-fsSL', '--retry', '3', '--connect-timeout', '20'];
const getText = (url) => run('curl', [...curlArgs, url], { capture: true });
const getJson = (url) => JSON.parse(getText(url));
const download = (url, file) => run('curl', [...curlArgs, '-o', file, url]);

function digest(file, algorithm, encoding) {
  const hash = createHash(algorithm);
  const data = readFileSync(file);
  hash.update(data);
  return hash.digest(encoding);
}

/** Streams large files through the hash (Codex archives are ~150 MB). */
async function digestStream(file, algorithm, encoding) {
  const hash = createHash(algorithm);
  for await (const chunk of createReadStream(file)) hash.update(chunk);
  return hash.digest(encoding);
}

/** The executable format and processor an ELF, Mach-O or PE file is built for. */
function binaryKind(file) {
  const head = Buffer.alloc(4096);
  const fd = openSync(file, 'r');
  let length;
  try {
    length = readSync(fd, head, 0, head.length, 0);
  } finally {
    closeSync(fd);
  }
  if (length < 4) return null;
  if (head.subarray(0, 4).equals(Buffer.from('\x7fELF', 'latin1'))) {
    const machine = head[5] === 1 ? head.readUInt16LE(18) : head.readUInt16BE(18);
    return { format: 'elf', arch: { 0x3e: 'x86_64', 0xb7: 'aarch64' }[machine] ?? 'other' };
  }
  if (head.readUInt32LE(0) === 0xfeedfacf || head.readUInt32BE(0) === 0xfeedfacf) {
    const cputype = head[0] === 0xcf ? head.readUInt32LE(4) : head.readUInt32BE(4);
    return { format: 'macho', arch: { 0x01000007: 'x86_64', 0x0100000c: 'aarch64' }[cputype] ?? 'other' };
  }
  if (head.readUInt32BE(0) === 0xcafebabe) return { format: 'macho', arch: 'universal' };
  if (head[0] === 0x4d && head[1] === 0x5a && length >= 0x40) {
    const pe = head.readUInt32LE(0x3c);
    if (pe + 6 > length || head.toString('latin1', pe, pe + 4) !== 'PE\0\0') return null;
    const machine = head.readUInt16LE(pe + 4);
    return { format: 'pe', arch: { 0x8664: 'x86_64', 0xaa64: 'aarch64' }[machine] ?? 'other' };
  }
  return null;
}

/** What `triple` runs, in the terms of `binaryKind`. */
function targetKind(triple) {
  const arch = triple.startsWith('x86_64-') ? 'x86_64' : triple.startsWith('aarch64-') ? 'aarch64' : null;
  const format = triple.includes('-apple-') ? 'macho' : triple.includes('-windows-') ? 'pe' : 'elf';
  return { format, arch };
}

function isExecutable(file) {
  const mode = statSync(file).mode;
  return process.platform === 'win32' || (mode & 0o111) !== 0;
}

/**
 * Why `file` is not a runtime for `triple`, or null. A recorded entry (from
 * versions.json) adds the checksum and size to the check.
 */
async function problemWith(file, triple, recorded) {
  if (!existsSync(file)) return 'missing';
  if (!statSync(file).isFile()) return 'not a file';
  const kind = binaryKind(file);
  if (!kind) return 'not an executable file (the download may be incomplete)';
  const wanted = targetKind(triple);
  if (kind.format !== wanted.format) {
    return `built for another operating system (${kind.format}, not ${wanted.format})`;
  }
  if (wanted.arch && kind.arch !== wanted.arch && !(kind.format === 'macho' && kind.arch === 'universal')) {
    return `built for another processor (${kind.arch}, not ${wanted.arch})`;
  }
  if (!isExecutable(file)) return 'not executable (chmod +x)';
  if (recorded?.sha256) {
    if (statSync(file).size !== recorded.size) return `size differs from the fetched ${recorded.version}`;
    if ((await digestStream(file, 'sha256', 'hex')) !== recorded.sha256) {
      return `checksum differs from the fetched ${recorded.version}`;
    }
  }
  return null;
}

function readVersions() {
  try {
    return JSON.parse(readFileSync(versionsFile, 'utf8'));
  } catch {
    return {};
  }
}

/** A recorded runtime: `{ version, sha256, size }`, or an older bare version string. */
function recordedEntry(versions, triple, name) {
  const entry = versions[triple]?.[name];
  if (typeof entry === 'string') return { version: entry };
  return entry && typeof entry === 'object' ? entry : undefined;
}

async function install(extracted, destination, triple) {
  copyFileSync(extracted, destination);
  chmodSync(destination, 0o755);
  const problem = await problemWith(destination, triple);
  if (problem) {
    rmSync(destination, { force: true });
    fail(`${destination} is ${problem}`);
  }
  return { sha256: await digestStream(destination, 'sha256', 'hex'), size: statSync(destination).size };
}

/** Whether the recorded runtime is present, intact and for the target. */
async function upToDate(name, destination, triple, recorded, version) {
  if (recorded?.version !== version) return false;
  // Recorded before checksums were kept: fetch again so they are.
  if (!recorded.sha256) return false;
  if ((await problemWith(destination, triple, recorded)) !== null) return false;
  console.log(`runtimes: ${name} ${version} is up to date`);
  return true;
}

/** Finds `name` anywhere under `dir` (archive layouts differ by platform). */
function findFile(dir, name) {
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const path = join(dir, entry.name);
    if (entry.isDirectory()) {
      const found = findFile(path, name);
      if (found) return found;
    } else if (entry.name === name) {
      return path;
    }
  }
  return null;
}

async function fetchCodex(triple, platform, exe, recorded, work) {
  const latest = getJson(`${CODEX_REGISTRY}/latest`);
  const version = latest.version;
  const destination = join(outDir, `codex-${triple}${exe}`);
  if (await upToDate('Codex', destination, triple, recorded, version)) return recorded;
  const alias = latest.optionalDependencies?.[`@openai/codex-${platform}`];
  const spec = alias?.startsWith('npm:@openai/codex@') ? alias.slice('npm:@openai/codex@'.length) : null;
  if (!spec) fail(`Codex ${version} has no package for ${platform}`);
  const manifest = getJson(`${CODEX_REGISTRY}/${encodeURIComponent(spec)}`);
  const integrity = manifest.dist?.integrity ?? '';
  if (!integrity.startsWith('sha512-')) fail('the Codex package has no sha512 integrity');

  console.log(`runtimes: downloading Codex ${version} (${platform})…`);
  const archive = join(work, 'codex.tgz');
  download(manifest.dist.tarball, archive);
  if ((await digestStream(archive, 'sha512', 'base64')) !== integrity.slice('sha512-'.length)) {
    fail('the Codex download does not match the registry checksum');
  }
  const member = run('tar', ['-tzf', archive], { capture: true })
    .split('\n')
    .map((line) => line.trim())
    .find((line) => new RegExp(`^package/vendor/[^/]+/bin/codex${exe.replace('.', '\\.')}$`).test(line));
  if (!member) fail('the Codex package does not contain the codex executable');
  run('tar', ['-xzf', archive, '-C', work, member]);
  const kept = await install(join(work, member), destination, triple);
  console.log(`runtimes: Codex ${version} → ${destination}`);
  return { version, ...kept };
}

async function fetchAnt(triple, [os, arch], exe, recorded, work) {
  const cask = getText(ANT_CASK);
  const version = /^\s*version\s+"([^"]+)"/m.exec(cask)?.[1];
  if (!version) fail('could not read the ant version from the Homebrew cask');
  const destination = join(outDir, `ant-${triple}${exe}`);
  if (await upToDate('ant', destination, triple, recorded, version)) return recorded;

  const fileName = `ant_${version}_${os}_${arch}.${os === 'linux' ? 'tar.gz' : 'zip'}`;
  let sha256 = null;
  // Each `url "…"` in the cask is followed by the `sha256 "…"` of that archive.
  for (const match of cask.matchAll(/url\s+"([^"]+)"\s+sha256\s+"([0-9a-f]{64})"/g)) {
    if (match[1].replaceAll('#{version}', version).endsWith(`/${fileName}`)) sha256 = match[2];
  }
  if (!sha256) {
    // Not in the cask (Windows): use the release's own checksums file.
    for (const name of [`ant_${version}_checksums.txt`, 'checksums.txt']) {
      try {
        const line = getText(`${ANT_RELEASES}/v${version}/${name}`)
          .split('\n')
          .find((l) => l.trim().endsWith(` ${fileName}`));
        if (line) sha256 = line.trim().split(/\s+/)[0];
      } catch {
        // Try the next name.
      }
      if (sha256) break;
    }
  }
  if (!sha256) fail(`no published checksum for ${fileName}`);

  console.log(`runtimes: downloading ant ${version} (${os} ${arch})…`);
  const archive = join(work, fileName);
  download(`${ANT_RELEASES}/v${version}/${fileName}`, archive);
  if (digest(archive, 'sha256', 'hex') !== sha256) {
    fail('the ant download does not match its published checksum');
  }
  const unpacked = join(work, 'unpacked');
  mkdirSync(unpacked);
  if (os === 'linux') {
    run('tar', ['-xzf', archive, '-C', unpacked]);
  } else if (!attempt('tar', ['-xf', archive, '-C', unpacked])) {
    // bsdtar (macOS, Windows) reads zip archives; GNU tar needs unzip.
    run('unzip', ['-q', archive, '-d', unpacked]);
  }
  const binary = findFile(unpacked, `ant${exe}`);
  if (!binary) fail('the ant archive does not contain the ant executable');
  const kept = await install(binary, destination, triple);
  console.log(`runtimes: ant ${version} → ${destination}`);
  return { version, ...kept };
}

/** `--check`: reports on the fetched runtimes for `triple` without any download. */
async function check(triple, exe, versions) {
  let problems = 0;
  for (const name of ['codex', 'ant']) {
    const file = join(outDir, `${name}-${triple}${exe}`);
    const recorded = recordedEntry(versions, triple, name);
    let problem = await problemWith(file, triple, recorded);
    if (!problem && !recorded?.sha256) problem = 'not recorded in versions.json (fetch it again)';
    if (problem) {
      problems += 1;
      console.error(`runtimes: ${file}: ${problem}`);
    } else {
      const size = statSync(file).size;
      console.log(`runtimes: ${name} ${recorded.version} ok (${(size / 1024 / 1024).toFixed(0)} MB, sha256 ${recorded.sha256.slice(0, 12)}…)`);
    }
  }
  if (problems) fail(`${problems} runtime(s) cannot be bundled for ${triple}`);
}

const triple = targetTriple();
if (triple === 'universal-apple-darwin') {
  fail('build one architecture at a time (aarch64-apple-darwin or x86_64-apple-darwin)');
}
const platform = PLATFORMS[triple];
if (!platform) fail(`no runtimes are published for ${triple}`);
const exe = triple.includes('windows') ? '.exe' : '';

mkdirSync(outDir, { recursive: true });
const versions = readVersions();
if (process.argv.includes('--check')) {
  await check(triple, exe, versions);
  process.exit(0);
}
const work = mkdtempSync(join(tmpdir(), 'rema-runtimes-'));
const record = (name, entry) => {
  versions[triple] = { ...versions[triple], [name]: entry };
  writeFileSync(versionsFile, `${JSON.stringify(versions, null, 2)}\n`);
};
try {
  const codexWork = join(work, 'codex');
  const antWork = join(work, 'ant');
  mkdirSync(codexWork);
  mkdirSync(antWork);
  record('codex', await fetchCodex(triple, platform.codex, exe, recordedEntry(versions, triple, 'codex'), codexWork));
  record('ant', await fetchAnt(triple, platform.ant, exe, recordedEntry(versions, triple, 'ant'), antWork));
  for (const name of [`codex-${triple}${exe}`, `ant-${triple}${exe}`]) {
    const size = statSync(join(outDir, name)).size;
    console.log(`runtimes: ${name} ${(size / 1024 / 1024).toFixed(0)} MB`);
  }
} finally {
  rmSync(work, { recursive: true, force: true });
}
