import type { PortfolioContent } from '../../services/portfolioService';

/** Fictional content that shows off a template in the gallery. */
export const SAMPLE_CONTENT: PortfolioContent = {
  header: {
    fullName: 'Alex Morgan',
    headline: 'Senior Data Engineer',
    email: 'alex.morgan@example.com',
    phone: '+43 660 000 0000',
    location: 'Vienna, Austria',
    website: '',
    linkedin: 'https://www.linkedin.com/in/alex-morgan-example',
    github: 'https://github.com/alex-morgan-example',
  },
  sections: [
    {
      id: 'summary',
      kind: 'summary',
      title: 'Summary',
      visible: true,
      text: 'Data engineer with eight years of experience building reliable streaming and batch platforms for analytics and machine learning teams.',
      entries: [],
    },
    {
      id: 'experience',
      kind: 'experience',
      title: 'Experience',
      visible: true,
      text: '',
      entries: [
        {
          id: 'e1',
          title: 'Senior Data Engineer',
          subtitle: 'Northwind Analytics',
          location: 'Vienna',
          start: '2021-03',
          end: 'Present',
          url: '',
          description:
            '- Led the move to an event-driven platform processing 2 billion events a day\n- Cut pipeline costs by 35% with incremental models\n- Mentored four engineers',
          tags: [],
        },
        {
          id: 'e2',
          title: 'Data Engineer',
          subtitle: 'Contoso Retail',
          location: 'Munich',
          start: '2017-09',
          end: '2021-02',
          url: '',
          description: '- Built the company’s first data warehouse and self-service dashboards\n- Introduced data quality checks on every release',
          tags: [],
        },
      ],
    },
    {
      id: 'education',
      kind: 'education',
      title: 'Education',
      visible: true,
      text: '',
      entries: [
        {
          id: 'd1',
          title: 'MSc Computer Science',
          subtitle: 'TU Wien',
          location: 'Vienna',
          start: '2015',
          end: '2017',
          url: '',
          description: '',
          tags: [],
        },
      ],
    },
    {
      id: 'skills',
      kind: 'skills',
      title: 'Skills',
      visible: true,
      text: '',
      entries: [
        {
          id: 's1',
          title: 'Data',
          subtitle: '',
          location: '',
          start: '',
          end: '',
          url: '',
          description: '',
          tags: ['Python', 'SQL', 'Apache Kafka', 'Spark', 'dbt'],
        },
        {
          id: 's2',
          title: 'Cloud',
          subtitle: '',
          location: '',
          start: '',
          end: '',
          url: '',
          description: '',
          tags: ['AWS', 'Terraform', 'Kubernetes'],
        },
      ],
    },
    {
      id: 'languages',
      kind: 'languages',
      title: 'Languages',
      visible: true,
      text: '',
      entries: [
        { id: 'l1', title: 'English', subtitle: 'C2', location: '', start: '', end: '', url: '', description: '', tags: [] },
        { id: 'l2', title: 'German', subtitle: 'Native', location: '', start: '', end: '', url: '', description: '', tags: [] },
      ],
    },
  ],
};
