// Every IPC command ReMa exposes, by name.
//
// `build.rs` includes this file to generate the permission set
// `app-commands`, which `capabilities/default.json` grants to the `main`
// webview only. Because the app declares these commands in its ACL
// manifest, Tauri checks every call against that capability: content in any
// other webview (the browser workspace) cannot call a single command.
// `ipc::tests::every_command_is_permissioned` keeps this list in sync.

pub const APP_COMMANDS: &[&str] = &[
    // System
    "get_app_status",
    "get_system_timezone",
    "open_external_url",
    "set_appearance",
    // Providers & models
    "get_provider_settings",
    "get_model_catalog",
    "connect_provider",
    "disconnect_provider",
    "save_custom_provider",
    "refresh_provider_models",
    "set_model_enabled",
    "set_default_model",
    "start_provider_sign_in",
    "cancel_provider_sign_in",
    "check_provider_connection",
    "sign_out_provider",
    // Connectors (Gmail, Google Calendar, Outlook Mail, Outlook Calendar)
    "get_connectors",
    "connect_connector",
    "cancel_connector_sign_in",
    "disconnect_connector",
    "set_background_settings",
    // Network Connect
    "network_capabilities",
    "network_research",
    "network_cancel",
    "network_last_result",
    "network_contacts",
    "import_network_contacts",
    "clear_network_contacts",
    // Business
    "business_overview",
    "business_save_profile",
    "business_create_offer",
    "business_save_offer_draft",
    "business_review_offer",
    "business_archive_offer",
    "business_delete_offer",
    "business_offer_version",
    "business_describe_offer",
    "business_describe_offer_document",
    "business_find_clients",
    "business_find_contracts",
    "business_cancel",
    "business_last_results",
    "business_runs",
    "business_pipeline",
    "business_save_prospect",
    "business_save_contract",
    "business_create_opportunity",
    "business_edit_opportunity",
    "business_change_stage",
    "business_record_activity",
    "business_delete_activity",
    "business_do_not_contact",
    "business_suppress_contact",
    "business_lift_suppression",
    "business_delete_contact",
    "business_delete_opportunity",
    "business_refresh_listing",
    "business_reassess",
    "business_redactions",
    "business_create_plan",
    "business_save_plan",
    "business_delete_plan",
    "business_research_plan",
    "business_target_accounts",
    "business_positioning",
    "business_create_draft",
    "business_update_draft",
    "business_delete_draft",
    "business_create_experiment",
    "business_update_experiment",
    "business_set_experiment_status",
    "business_amend_experiment",
    "business_delete_experiment",
    "business_experiment_metrics",
    // Applications tracker & notifications
    "get_applications",
    "get_calendar",
    "get_application",
    "set_application_status",
    "add_interview_to_calendar",
    "decline_interview_calendar",
    "list_notifications",
    "mark_notifications_read",
    "clear_notifications",
    // Profile
    "get_profile",
    "save_profile",
    "add_profile_document",
    "import_profile_document",
    "update_profile_document",
    "delete_profile_document",
    "open_profile_document",
    "add_profile_documents",
    "replace_profile_document",
    "set_primary_document",
    "profile_document_blocks",
    "save_credential",
    "delete_credential",
    // Portfolio Studio
    "list_portfolios",
    "create_portfolio",
    "get_portfolio",
    "rename_portfolio",
    "import_portfolio_file",
    "import_portfolio_document",
    "portfolio_ai_assist",
    "save_portfolio",
    "duplicate_portfolio",
    "delete_portfolio",
    "export_portfolio_pdf",
    // Agents
    "list_agents",
    "save_agent",
    "duplicate_agent",
    "delete_agent",
    // Web search service
    "career_search_status",
    "check_career_search",
    "set_answer_mode",
    "web_search_settings",
    "save_web_search_settings",
    "test_web_search",
    // ReMa MCP (built in)
    "rema_mcp_status",
    "set_rema_mcp_enabled",
    "clear_rema_mcp_cache",
    "rema_mcp_launch",
    "add_rema_mcp_to",
    // MCP servers
    "list_mcp_servers",
    "save_mcp_server",
    "delete_mcp_server",
    "set_mcp_server_enabled",
    "connect_mcp_server",
    "disconnect_mcp_server",
    "test_mcp_server",
    "sign_in_mcp_server",
    "cancel_mcp_sign_in",
    "sign_out_mcp_server",
    "mcp_import_sources",
    "preview_mcp_import",
    "import_mcp_servers",
    // Browser workspace & Auto Fill
    "get_browser_status",
    "open_in_browser",
    "set_browser_bounds",
    "set_browser_visible",
    "browser_back",
    "browser_forward",
    "browser_reload",
    "close_browser",
    "run_autofill",
    "attach_profile_document",
    "reveal_profile_document",
    // Chat
    "list_conversations",
    "get_conversation",
    "send_message",
    "retry_message",
    "stop_generation",
    "delete_conversation",
    "set_conversation_selections",
    "respond_tool_approval",
    // Scheduled tasks
    "list_tasks",
    "create_task",
    "update_task",
    "set_task_enabled",
    "delete_task",
    "run_task_now",
    "list_task_runs",
    "get_task_run",
    "cancel_task_run",
    // Job analytics
    "get_analytics_preferences",
    "save_analytics_preferences",
    "list_job_search_runs",
    "delete_job_search_run",
    "get_analytics_overview",
    "get_skill_gap",
    "get_requirements_analysis",
    "get_learning",
    "research_learning",
    "analyze_answer",
    "analyze_task_result",
    "list_conversation_job_runs",
    "list_task_job_runs",
];
